kumuluzee:
  name: iskalec-vaj
  version: 0.0.1
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/baza
      connection-url: jdbc:postgresql://localhost:5432/iskalec_vaj
      username: postgres
      password: postgres
      max-pool-size: 20
email:
  host: smtp.gmail.com
  port: 587
  username: playernobody@gmail.com
  password: jljyjoaipsjojvbi